name: build_downport_branch

on:
  push:
    branches: [main]

jobs:
  build_downpor_branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: 702

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - run: npm ci
    - run: npm run downport
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        branch: auto-update-downport
        title: "Auto Update Downport"
        commit-message: "Auto Update Downport"
        body: "This PR contains automated changes."
        labels: "auto-merge"
    - name: Enable Pull Request Automerge
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
        merge-method: squash  
